### ISSUE TITLE
Link file support

### ISSUE THREAD

**Issue by naavis** [bentley/rgbds#106]
Are link files supported at all anymore? I'm trying to link RGBGrafx into my project, but passing the link file by calling `rgblink LinkFileName`  outputs _rgblink: 'LinkFileName' is not a valid object_, as if it is expecting an object file. The command line arguments seem to have changed significantly, but the HTML documentation is not up-to-date.

**Comment by AntonioND** [comment]
You are right, link files aren't supported anymore, now you have to pass the list of object files to rgblink from the command line.
