### ISSUE TITLE
Macro already defined

### ISSUE THREAD

**Issue by naavis** [bentley/rgbds#108]
I'm having trouble using macros with rgbasm. If I define a macro and call it, the assembler seems to think I'm trying to define it twice.

```asm
Foo: MACRO
ENDM

Foo
```

Assembling this snippet outputs the error _'Foo' already defined_. Am I missing something here?

**Comment by AntonioND** [comment]
Add a space or tabulation before the name of the macro when you call it.

**Comment by naavis** [comment]
That did the trick, thanks. I didn't see a mention of this in the documents.
