### ISSUE TITLE
Feature request: Write all symbols into symfile

### ISSUE THREAD

**Issue by Sanqui** [bentley/rgbds#35]
As is, symbols (labels) which aren't referenced aren't written in the symfile.  An option to write them all would be nice.

**Comment by derivator** [comment]
Subroutines that are only referenced by relative jumps are also sadly not included.

**Comment by AntonioND** [comment]
That's a problem of the assembler, the linker writes all symbols it sees, but the assembler doesn't write to the object files all the labels. It's a shame.

**Comment by AntonioND** [comment]
Wasn't this fixed here? https://github.com/bentley/rgbds/pull/80

**Comment by Sanqui** [comment]
Oh hey, yeah!  Go me!
