### ISSUE TITLE
rgblink segfault

### ISSUE THREAD

**Issue by RenaKunisaki** [bentley/rgbds#65]
https://github.com/RenaKunisaki/pokered

This had been building fine a while ago, but after merging a newer version of the original pokered and fixing some labels, rgblink segfaults when running `make red`.

**Comment by bentley** [comment]
Please create a minimal testcase.

**Comment by RenaKunisaki** [comment]
My bad, seems like it was just the issue already fixed in commit 116569f54d6464421278c96d4ae638787e7d305a.
