### ISSUE TITLE
RGBLINK fails when assigning banks > 255.

### ISSUE THREAD

**Issue by AntonioND** [bentley/rgbds#66]
https://github.com/bentley/rgbds/blob/master/src/link/symbol.c#L79
https://github.com/bentley/rgbds/blob/master/include/link/symbol.h#L7
Change the last argument in both lines by: "SLONG nBank"

b0.asm:
```
GLOBAL LABEL_B258
SECTION "INIT",ROM0[0]
DW BANK(LABEL_B258)
```

b1.asm:
```
SECTION "GBT_BANK0",ROMX,BANK[258]
LABEL_B258:: DB 0
```

Make ROM:
```
rgbasm -ob0.o b0.asm
rgbasm -ob1.o b1.asm
rgblink -o out.gb b0.o b1.o
```

Should output 02 01 FF FF ...

**Comment by bentley** [comment]
Fixed in 6c10ca62ad899fe5f5f0f687d7ec7b3b0650601f, thanks.
