### ISSUE TITLE
GB graphic prefix bug

### ISSUE THREAD

**Issue by fransrz** [bentley/rgbds#87]
When you define a _GB graphic_ constant, like **DW `00133100** the resulting two bytes of _planar_ data seem to get stored in the wrong order. It should store the least significant bits first and the most significant ones after them.

Currently **DW `00133100** results in **$18 $3C** being stored instead of **$3C $18**.

Due to this bug, all pixels with ligh-gray or dark-gray shades get swapped.

**Comment by AntonioND** [comment]
I'll try to take a look at it this weekend, but at least I've looked for the location of the bug if someone wants to do it before: https://github.com/bentley/rgbds/blob/master/src/asm/globlex.c#L83

**Comment by bentley** [comment]
@AntonioND fixed this in fbb825af3b5ee5c24d4633e06320759bc1d08179.
