### ISSUE TITLE
rgbfix doc

### ISSUE THREAD

**Issue by romhack** [bentley/rgbds#91]
There is no document for rgbfix, though other documents refers to it as "fix.htm"

**Comment by nicklausw** [comment]
Thought there was existing (html format) documentation for it online that had been removed but only found: http://diyhpl.us/~yenatch/irc/rgbfix.1

**Comment by romhack** [comment]
I suspect [this](https://github.com/vegard/rgbds-linux/blob/master/doc/fix.htm) can be the original document. Not sure, if content needs update - flags changes etc...

**Comment by bentley** [comment]
rgbfix was rewritten from scratch a long time ago, and `fix.html` no longer applies. It’s documented instead by `src/fix/rgbfix.1`. #84 rightly points out that generated documentation (HTML or PDF) should be included in the release zips.

Bringing the documentation up to date in general is a long‐standing bug.

**Comment by romhack** [comment]
OK, hope to see html for windows users in future releases. Thanks.
